apiVersion: apps/v1
kind: Deployment
metadata:
  name: cors-proxy
  labels:
    app: cors-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cors-proxy
  template:
    metadata:
      labels:
        app: cors-proxy
    spec:
      containers:
        - name: cors-proxy
          image: robinsthedev/cors-anywhere:latest
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "500m"
